name = "reddit_clone"
version = "0.1.0"

[dependencies]
gleam_stdlib = ">= 0.65.0 and < 1.0.0"
gleam_otp = ">= 1.2.0 and < 2.0.0"
gleam_erlang = ">= 0.9.0 and < 2.0.0"
gleam_time = ">= 1.5.0 and < 2.0.0"
prng = ">= 4.0.1 and < 5.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
